'''
Script for holding constants for the prompt generation process

Most of these are long lists of actions and phrases. 
'''
actions = [
    "get a haircut",
    "attend a yoga class",
    "meet with a client",
    "visit the dentist",
    "have a date night",
    "schedule a doctor's appointment",
    "watch a movie with friends",
    "attend a parent-teacher conference",
    "go for a jog",
    "call a family meeting",
    "buy groceries",
    "pick up dry cleaning",
    "attend a job interview",
    "have a business meeting",
    "meet with a personal trainer",
    "go to a concert",
    "volunteer at a local charity",
    "take the dog for a walk",
    "have a spa day",
    "meet with a financial advisor",
    "go on a shopping spree",
    "plan a weekend getaway",
    "meet for a coffee date",
    "attend a workshop",
    "go to a tech conference",
    "plan a surprise party",
    "visit a museum",
    "set up a playdate for the kids",
    "attend a networking event",
    "join a support group",
    "host a dinner party",
    "have a therapy session",
    "attend a cooking class",
    "go on a hiking trip",
    "meet with a real estate agent",
    "attend a book club meeting",
    "take a scenic drive",
    "have a romantic dinner",
    "visit an art gallery",
    "plan a beach day",
    "meet with a travel agent",
    "go to a poetry reading",
    "have a picnic in the park",
    "attend a language class",
    "take a dance lesson",
    "meet with a nutritionist",
    "go on a museum tour",
    "plan a family reunion",
    "enjoy a spa massage",
    "meet with a life coach",
    "attend a cooking competition",
    "take a scenic bike ride",
    "go to a themed party",
    "host a barbecue cookout",
    "plan a romantic getaway",
    "have a picnic in the countryside",
    "meet with a career counselor",
    "participate in a charity run",
    "go to a local farmers' market",
    "attend a pet adoption event",
    "have a game night with friends",
    "plan a visit to a botanical garden",
    "enjoy a scenic train ride",
    "meet with a travel blogger",
    "go to a local art exhibition",
    "attend a stand-up comedy show",
    "have a family movie night",
    "visit a historical landmark",
    "plan a visit to an amusement park",
    "go to a karaoke night",
    "host a potluck dinner",
    "attend a wine tasting event",
    "take a nature hike",
    "meet with a personal stylist",
    "go to a craft fair",
    "plan a visit to an aquarium",
    "have a game of mini-golf",
    "visit a wildlife sanctuary",
    "attend a poetry slam",
    "go to a car show",
    "host a themed costume party",
    "plan a day at the beach",
    "meet with a tattoo artist",
    "go to a themed escape room",
    "attend a lecture on art history",
    "have a science experiment day",
    "visit a botanical garden",
    "plan a visit to a space museum",
    "go to a trampoline park",
    "host a talent show",
    "attend a food festival",
    "take a painting class",
    "meet with a life coach",
    "go to a dance competition",
    "plan a visit to a planetarium",
    "have a karaoke night with friends",
    "visit a wildlife reserve",
    "attend a local theater performance",
    "go to a storytelling event",
    "host a board game night",
    "plan a visit to a science center",
    "meet with a nutritionist",
    "go to a classic car show",
    "have a spa day with friends",
    "visit an outdoor art exhibit",
    "attend a jazz music concert",
    "go to a cooking workshop",
    "host a barbecue party",
    "plan a visit to a tropical garden",
    "meet with a wellness coach",
    "go to a petting zoo",
    "have a photography workshop",
    "visit a children's science museum",
    "attend a live theater performance",
    "go to a dance recital",
    "host a craft night with friends",
    "plan a visit to a botanical conservatory",
    "meet with a financial advisor",
    "go to a stand-up comedy club",
    "have a tea tasting with friends",
    "visit an interactive science museum",
    "attend a photography exhibit",
    "go to a wine and paint night",
    "host a themed trivia night",
    "plan a visit to a butterfly garden",
    "meet with a pet trainer",
    "go to a documentary screening",
    "have a puzzle-solving competition",
    "visit a marine life sanctuary",
    "attend a live music festival",
    "go to a DIY crafting workshop",
    "host a themed costume party",
    "plan a visit to a historic mansion",
    "meet with a life coach",
    "go to a board game cafe",
    "have a themed movie night with friends",
    "visit a wildlife rehabilitation center",
    "attend a circus performance",
    "go to a pottery painting class",
    "host a charity fundraising event",
    "plan a visit to a planetarium",
    "meet with a tarot card reader",
    "go to a comedy improv show",
    "have a sushi-making night with friends",
    "visit a local food truck festival",
    "attend a vintage car show",
    "go to a photography scavenger hunt",
    "host a scavenger hunt",
    "plan a visit to a hot air balloon festival",
    "meet with a personal trainer",
    "go to a food and wine pairing event",
    "have a cupcake decorating competition",
    "visit a reptile sanctuary",
    "attend a magic show",
    "go to a classic film screening",
    "host a themed costume party",
    "plan a visit to a historic castle",
    "meet with a relationship counselor",
    "go to a stand-up comedy club",
    "have a themed cooking competition with friends",
    "visit a botanical garden",
    "attend a garden party",
    "go to a wine and cheese tasting event",
    "host a themed game night",
    "plan a visit to a butterfly conservatory",
    "meet with a personal coach",
    "go to a bird-watching expedition",
    "have a puzzle-solving challenge with friends",
    "visit a wildlife rescue center",
    "attend a live jazz music performance",
    "go to a photography exhibition",
    "host a pottery painting night",
    "plan a visit to a historic lighthouse",
    "meet with a yoga instructor",
    "go to a comedy club",
    "have a themed movie marathon",
    "visit a local food and wine festival",
    "attend a vintage clothing expo",
    "go to a photography workshop",
    "host a charity auction event",
    "plan a visit to an observatory",
    "meet with a palm reader",
    "go to an improv theater show",
    "have a chocolate-tasting night with friends",
    "visit a chocolate factory tour",
    "attend a classic car exhibit",
    "go to a DIY home improvement workshop",
    "host a board game night with friends",
    "plan a visit to a historical village",
    "meet with a career counselor",
    "go to a local theater play",
    "have a themed costume party with friends",
    "visit a tropical bird sanctuary",
    "attend a live stand-up comedy show",
    "go to a wine and painting night",
    "host a themed trivia game night",
    "plan a visit to a botanical rainforest",
    "meet with a wellness coach",
    "go to a pet adoption event",
    "have a craft beer tasting with friends",
    "visit an art and wine gallery",
    "attend a photography class",
    "go to a cooking competition",
    "host a potluck dinner",
    "plan a visit to a historical reenactment",
    "meet with a personal trainer",
    "go to a dance competition",
    "have a karaoke night with friends",
    "visit a wildlife reserve",
    "attend a local theater performance",
    "go to a storytelling event",
    "host a board game night",
    "plan a visit to a science center",
    "meet with a nutritionist",
    "go to a classic car show",
    "have a spa day with friends",
    "visit an outdoor art exhibit",
    "attend a jazz music concert",
    "go to a cooking workshop",
    "host a barbecue party",
    "plan a visit to a tropical garden",
    "meet with a wellness coach",
    "go to a petting zoo",
    "have a photography workshop",
    "visit a children's science museum",
    "attend a live theater performance",
    "go to a dance recital",
    "host a craft night with friends",
    "plan a visit to a botanical conservatory",
    "meet with a financial advisor",
    "go to a stand-up comedy club",
    "have a tea tasting with friends",
    "visit an interactive science museum",
    "attend a photography exhibit",
    "go to a wine and paint night",
    "host a themed trivia night",
    "plan a visit to a butterfly garden",
    "meet with a pet trainer",
    "go to a documentary screening",
    "have a puzzle-solving competition",
    "visit a marine life sanctuary",
    "attend a live music festival",
    "go to a DIY crafting workshop",
    "host a themed costume party",
    "plan a visit to a historic mansion",
    "meet with a life coach",
    "go to a board game cafe",
    "have a themed movie night with friends",
    "visit a wildlife rehabilitation center",
    "attend a circus performance",
    "go to a pottery painting class",
    "host a charity fundraising event",
    "plan a visit to a planetarium",
    "meet with a tarot card reader",
    "go to a comedy improv show",
    "have a sushi-making night with friends",
    "visit a local food truck festival",
    "attend a vintage car show",
    "go to a photography scavenger hunt",
    "host a scavenger hunt",
    "plan a visit to a hot air balloon festival",
    "meet with a personal trainer",
    "go to a food and wine pairing event",
    "have a cupcake decorating competition",
    "visit a reptile sanctuary",
    "attend a magic show",
    "go to a classic film screening",
    "host a themed costume party",
    "plan a visit to a historic castle",
    "meet with a relationship counselor",
    "go to a stand-up comedy club",
    "have a themed cooking competition with friends",
    "visit a botanical garden",
    "attend a garden party",
    "go to a wine and cheese tasting event",
    "host a themed game night",
    "plan a visit to a butterfly conservatory",
    "meet with a personal coach",
    "go to a bird-watching expedition",
    "have a puzzle-solving challenge with friends",
    "visit a wildlife rescue center",
    "attend a live jazz music performance",
    "go to a photography exhibition",
    "host a pottery painting night",
    "plan a visit to a historic lighthouse",
    "meet with a yoga instructor",
    "go to a comedy club",
    "have a themed movie marathon",
    "visit a local food and wine festival",
    "attend a vintage clothing expo",
    "go to a photography workshop",
    "host a charity auction event",
    "plan a visit to an observatory",
    "meet with a palm reader",
    "go to an improv theater show",
    "have a chocolate-tasting night with friends",
    "visit a chocolate factory tour",
    "attend a classic car exhibit",
    "go to a DIY home improvement workshop",
    "host a board game night with friends",
    "plan a visit to a historical village",
    ]

eval_actions = [
    "take a pottery class",
    "go on a wine tour",
    "visit a botanical park",
    "plan a day at the zoo",
    "meet with a personal chef",
    "attend a science fair",
    "have a movie marathon",
    "go on a road trip",
    "host a themed costume party",
    "schedule a spa day",
    "meet for a coffee date",
    "visit an escape room",
    "plan a visit to an art museum",
    "have a picnic by the lake",
    "go to a farmers' market",
    "watch a live theater performance",
    "organize a charity run",
    "meet with a life coach",
    "go on a photography expedition",
    "host a board game night",
    "attend a poetry reading",
    "take a scenic helicopter ride",
    "visit a wildlife sanctuary",
    "plan a visit to a botanical conservatory",
    "meet with a financial advisor",
    "go to a stand-up comedy show",
    "have a tea tasting with friends",
    "go on a museum tour",
    "attend a cooking competition",
    "take a scenic bike ride",
    "visit an outdoor art exhibit",
    "host a barbecue cookout",
    "plan a romantic getaway",
    "have a picnic in the countryside",
    "meet with a career counselor",
    "participate in a charity walk",
    "go to a local art exhibition",
    "attend a live music festival",
    "watch a live sports game",
    "organize a treasure hunt",
    "host a craft night with friends",
    "schedule a wine and cheese tasting",
    "meet for a game night",
    "go on a hot air balloon ride",
    "visit a historical castle",
    "plan a visit to a space museum",
    "have a spa day with friends",
    "meet with a travel blogger",
    "go to a petting zoo",
    "attend a children's science museum",
    "take a dance lesson",
    "host a themed trivia night",
    "plan a visit to a butterfly garden",
    "meet with a pet trainer",
    "go on a documentary screening",
    "have a puzzle-solving competition",
    "visit a marine life sanctuary",
    "attend a vintage car show",
    "go on a shopping spree",
    "plan a visit to a historic mansion",
    "meet with a life coach",
    "go to a board game cafe",
    "have a themed movie night with friends",
    "attend a circus performance",
    "watch a live magic show",
    "organize a painting workshop",
    "host a charity fundraising event",
    "schedule a visit to an observatory",
    "meet with a palm reader",
    "go on an improv theater show",
    "have a sushi-making night with friends",
    "visit a local food truck festival",
    "take a cooking class",
    "plan a visit to an aquarium",
    "attend a stand-up comedy club",
    "meet for a game of mini-golf",
    "go on a wildlife safari",
    "host a karaoke night",
    "schedule a nature hike",
    "visit an art and wine gallery",
    "have a cupcake decorating competition",
    "meet with a personal stylist",
    "go on a historic train ride",
    "plan a visit to a tropical garden",
    "attend a wine tasting event",
    "watch a live jazz music concert",
    "organize a scavenger hunt",
    "host a themed costume party with friends",
    "take a scenic cruise",
    "go to a bird-watching expedition",
    "meet with a wellness coach",
    "visit an indoor trampoline park",
    "have a puzzle-solving challenge with friends",
    "attend a local theater play",
    "go on a pottery painting class",
    "plan a visit to a wildlife rehabilitation center",
    "meet with a travel agent",
    "schedule a visit to a planetarium",
    "organize a night of comedy improv",
    "host a chocolate-tasting night with friends",
    "take a trip to a chocolate factory",
    "meet for a classic film screening",
    "go on a DIY home improvement workshop",
    "visit an interactive science museum",
    "have a family game night",
    "plan a visit to a butterfly conservatory",
    "attend a photography class",
    "watch a wine and paint night",
    "meet with a personal coach",
    "go on a pet adoption event",
    "schedule a themed cooking competition",
    "visit an exotic botanical garden",
    "organize a garden party",
    "have a movie marathon with friends",
    "meet for a wine and cheese tasting event",
    "go on a hike to a scenic waterfall",
    "host a board game night with friends",
    "take a scenic hot air balloon ride",
    "attend a vintage clothing expo",
    "go on a photography workshop",
    "plan a visit to a wildlife rescue center",
    "meet with a relationship counselor",
    "organize a themed trivia night",
    "host a game night with friends",
    "schedule a visit to a historic lighthouse",
    "go on a visit to a yoga retreat",
    "meet with a yoga instructor",
    "have a tea tasting party with friends",
    "visit a classic car exhibit",
    "attend a local theater performance",
    "watch a live music festival",
    "plan a visit to a comedy club",
    "go on a pottery painting night",
    "organize a dance competition",
    "host a stand-up comedy show",
    "take a scenic horseback ride",
    "meet for a craft night with friends",
    "schedule a visit to a botanical rainforest",
    "visit an outdoor art exhibit",
    "have a barbecue party with friends",
    "go on a visit to a tropical garden",
    "meet with a wellness coach",
    "plan a visit to a petting zoo",
    "attend a documentary screening",
    "organize a craft beer tasting night",
    "watch a themed costume party",
    "host a spa day with friends",
    "take a scenic boat tour",
    "meet for a karaoke night",
    "schedule a wildlife safari",
    "visit a wildlife reserve",
    "plan a visit to a children's science museum",
    "attend a live theater performance",
    "go on a dance recital",
    "organize a classic film screening",
    "host a craft night with friends",
    "watch a live jazz music concert",
    "take a visit to an art gallery",
    "meet with a nutritionist",
    "schedule a cooking workshop",
    "visit a science center",
    "have a themed costume party",
    "organize a board game night",
    "go on a visit to a classic car show",
    "meet with a pet trainer",
    "watch a themed trivia night",
    "host a spa day with friends",
    "take a pottery class",
    "visit a botanical park",
    "plan a day at the zoo",
    "meet with a personal chef",
    "attend a science fair",
    "have a movie marathon",
    "go on a road trip",
    "host a themed costume party",
    "schedule a spa day",
    "meet for a coffee date",
    "visit an escape room",
    "plan a visit to an art museum",
    "have a picnic by the lake",
    "go to a farmers' market",
    "watch a live theater performance",
    "organize a charity run",
    "meet with a life coach",
    "go on a photography expedition",
    "host a board game night",
    "attend a poetry reading",
    "take a scenic helicopter ride",
    "visit a wildlife sanctuary",
    "plan a visit to a botanical conservatory",
    "meet with a financial advisor",
    "go to a stand-up comedy show",
    "have a tea tasting with friends",
    "go on a museum tour",
    "attend a cooking competition",
    "take a scenic bike ride",
    "visit an outdoor art exhibit",
    "host a barbecue cookout",
    "plan a romantic getaway",
    "have a picnic in the countryside",
    "meet with a career counselor",
    "participate in a charity walk",
    "go to a local art exhibition",
    "attend a live music festival",
    "watch a live sports game",
    "organize a treasure hunt",
    "host a craft night with friends",
    "schedule a wine and cheese tasting",
    "meet for a game night",
    "go on a hot air balloon ride",
    "visit a historical castle",
    "plan a visit to a space museum",
    "have a spa day with friends",
    "meet with a travel blogger",
    "go to a petting zoo",
    "attend a children's science museum",
    "take a dance lesson",
    "host a themed trivia night",
    "plan a visit to a butterfly garden",
    "meet with a pet trainer",
    "go on a documentary screening",
    "have a puzzle-solving competition",
    "visit a marine life sanctuary",
    "attend a vintage car show",
    "go on a shopping spree",
    "plan a visit to a historic mansion",
    "meet with a life coach",
    "go to a board game cafe",
    "have a themed movie night with friends",
    "attend a circus performance",
    "watch a live magic show",
    "organize a painting workshop",
    "host a charity fundraising event",
    "schedule a visit to an observatory",
    "meet with a palm reader",
    "go on an improv theater show",
    "have a chocolate-tasting night with friends",
    "visit a chocolate factory tour",
    "attend a classic car exhibit",
    "go to a DIY home improvement workshop",
    "host a board game night with friends",
    "plan a visit to a historical village",
]

small_actions = [
    "plan a hiking trip",
    "have a picnic in the mountains",
    "go on a camping adventure",
    "attend a wine and cheese tasting event",
    "take a photography workshop",
    "organize a beach cleanup",
    "visit an archaeological site",
    "host a themed costume party",
    "plan a visit to a historic lighthouse",
    "have a spa day with friends",
    "meet with a wellness coach",
    "attend a local food and wine festival",
    "go on a photography workshop",
    "organize a charity auction event",
    "visit an observatory",
    "have a movie night under the stars",
    "plan a visit to a botanical rainforest",
    "meet with a yoga instructor",
    "attend a vintage clothing expo",
    "go on a pottery painting class",
    "host a craft beer tasting with friends",
    "take a scenic boat tour",
    "visit a wildlife reserve",
    "organize a board game night",
    "plan a visit to a classic car show",
    "have a themed trivia night",
    "meet with a pet trainer",
    "go on a pottery class",
    "take a wine tour",
    "visit a botanical park",
    "plan a day at the zoo",
    "meet with a personal chef",
    "attend a science fair",
    "go on a road trip",
    "schedule a spa day",
    "plan a visit to an art museum",
    "have a picnic by the lake",
    "go to a farmers' market",
    "watch a live theater performance",
    "organize a charity run",
    "meet with a life coach",
    "go on a photography expedition",
    "host a board game night",
    "attend a poetry reading",
    "take a scenic helicopter ride",
    "plan a visit to a botanical conservatory",
    "meet with a financial advisor",
    "go to a stand-up comedy show",
    "have a tea tasting with friends",
    "go on a museum tour",
    "attend a cooking competition",
    "take a scenic bike ride",
    "visit an outdoor art exhibit",
    "host a barbecue cookout",
    "plan a romantic getaway",
    "have a picnic in the countryside",
    "meet with a career counselor",
    "participate in a charity walk",
    "go to a local art exhibition",
    "attend a live music festival",
    "watch a live sports game",
    "organize a treasure hunt",
    "host a craft night with friends",
    "schedule a wine and cheese tasting",
    "meet for a game night",
    "go on a hot air balloon ride",
    "visit a historical castle",
    "plan a visit to a space museum",
    "have a spa day with friends",
    "meet with a travel blogger",
    "go to a petting zoo",
    "attend a children's science museum",
    "take a dance lesson",
    "host a themed trivia night",
    "plan a visit to a butterfly garden",
    "meet with a pet trainer",
    "go on a documentary screening",
    "have a puzzle-solving competition",
    "visit a marine life sanctuary",
    "attend a vintage car show",
    "go on a shopping spree",
    "plan a visit to a historic mansion",
    "meet with a life coach",
    "go to a board game cafe",
    "have a themed movie night with friends",
    "attend a circus performance",
    "watch a live magic show",
    "organize a painting workshop",
    "host a charity fundraising event",
    "schedule a visit to an observatory",
    "meet with a palm reader",
    "go on an improv theater show",
    "have a chocolate-tasting night with friends",
    "visit a chocolate factory tour",
    "attend a classic car exhibit",
    "go to a DIY home improvement workshop",
    "host a board game night with friends",
    "plan a visit to a historical village",
    "go on a visit to a yoga retreat",
    "meet with a yoga instructor",
    "have a tea tasting party with friends",
    "visit a classic car exhibit",
]

